name: Push image (REUSABLE)

on:
  workflow_call:
    inputs:
      IMAGE:
        required: true
        type: string
      TAGS:
        required: true
        type: string
      CACHE_FROM:
        required: true
        type: string
      DOCKERFILE:
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true
      ARM_SSH_KEY:
        required: true
      ARM_SSH_CONFIG:
        required: true
      ARM_SSH_IP:
        required: true

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      # Prepare
      - name: Check out repository code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Login to Docker Hub
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Login to ghcr
        uses: docker/login-action@9780b0c442fbb1117ed29e0efdff1e18412f7567 # v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      # Compute metadata
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        with:
          images: bunkerity/${{ inputs.IMAGE }}
      # Build and push
      - name: Build and push
        uses: docker/build-push-action@4f58ea79222b3b9dc2c8bbdd6debcef730109a75 # v6.9.0
        with:
          context: .
          file: ${{ inputs.DOCKERFILE }}
          platforms: linux/amd64,linux/386
          push: true
          tags: ${{ inputs.TAGS }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: |
            type=gha,scope=${{ inputs.CACHE_FROM }}-amd64
            type=gha,scope=${{ inputs.CACHE_FROM }}-386
